### ISSUE TITLE
AddProtocolModal Dialog no padding/margin in left end

### ISSUE THREAD

**Issue by anilhelvaci** [CrabblePitch/crabble-ui#11]
<img width="867" alt="image" src="https://github.com/CrabblePitch/crabble-ui/assets/32987478/4d443c12-3147-4084-b3f0-ef22dc0041f8">

**Comment by GrigoriGrigoryanBytepitch** [comment]
<img width="552" alt="image" src="https://github.com/CrabblePitch/crabble-ui/assets/125870999/4545fd01-a8a8-4478-9f67-3811eecfca05">
