### ISSUE TITLE
https://crabble.web.app not resolving on latest Chrome version due to Endo dependencies (SES update required)

### ISSUE THREAD

**Issue by otoole-brendan** [CrabblePitch/crabble-ui#34]
Bug description

Dapp does not resolve on latest version of Chrome - page just hangs

See below referenced fixes for other Agoric dapps:

https://github.com/Agoric/dapp-inter/issues/242

https://github.com/Agoric/dapp-psm/pull/121

https://github.com/Agoric/dapp-psm/pull/123

Repro
Go to https://crabble.web.app/ on latest version of Chrome -> does not resolve

Expected behavior
Should load

Branch
No response

Connected Network
Mainnet

**Comment by anilhelvaci** [comment]
Closed with https://github.com/CrabblePitch/crabble-ui/commit/54718420f40f63a1e59c3721fcbebc243dcff556
