### ISSUE TITLE
Implement `Bag` Page

### ISSUE THREAD

**Issue by anilhelvaci** [CrabblePitch/crabble-ui#8]
The design: https://share.balsamiq.com/c/huMrbABqY4itDX9zckxgKK.png

**Comment by GrigoriGrigoryanBytepitch** [comment]
![telegram-cloud-photo-size-2-5193189058497597363-y](https://github.com/CrabblePitch/crabble-ui/assets/125870999/85c6d8dd-4cc7-49a6-a6bc-f33a9485051e)
